### ISSUE TITLE
Can't annotate EHMP Model

### ISSUE THREAD

**Issue by KenLord** [MDMI/MDMI#105]
Right click on attribute, select MDMI mapping, select Map Property. Nothing happens

**Comment by swmuir** [comment]
Pushed out update to model - currently the UI needs associations to properly map the element path
pull down the latest version of the model

**Comment by KenLord** [comment]
hi Sean,

Not sure what I am supposed to do.  I updated eclipse and tried annotating
and still cannot.

Am I missing something?

Ken

**Comment by swmuir** [comment]
right Click on the project and select team->pull
