### ISSUE TITLE
CCDA 1.1 Automation: RecordTarget Cardinality

### ISSUE THREAD

**Issue by KenLord** [MDMI/MDMI#11]
Not the best title. We should be generating an MDMI Map per document type instead of the entire model.  For example, RecordTarget can have a cardinality >1, but if someone sent a CCD document and happened to have two Record Targets, this would create issues.  We should be generating maps for the constrained CCDA documents.

Therefore, RecordTarget should have a cardinality of 1 and it should have an associated Semantic Element.

**Comment by swmuir** [comment]
Fixed
