### ISSUE TITLE
Runtime FHIR to FHIR = target message issues

### ISSUE THREAD

**Issue by KenLord** [MDMI/MDMI#112]
Using lastest models and runtime.
Ran ISOmorphically FHIR.  Source Message Patientbundle.xml and Target Message Targetbundle.xml.

No data in target message.  Source Semantic Model looks correct and target Model is blank. 

Also,
Error DatamapInterpreter: 156: Failed executing mapFHIR_dateTimeToDateTime : = No such function mapFHIR_dateTimeToDateTime

**Comment by swmuir** [comment]
We need the patient container added to the RI and then mapped

**Comment by KenLord** [comment]
OK.  Understand.

But this also happens to be the Beth Israel problem and I think we need to
discuss that sometime.

Ken

**Comment by swmuir** [comment]
I am not sure what there is to discuss - currently we leverage semantic containers to organize data - now this might not seem to make sense when logically we only have "one patient" to introduce such a container but we could have messages with multiple patients and there would be a semantic container 

our current limitation is that we are syntactically hierarchical  with our containers

when dealing with flattened data - you would need to expand the concept of a map to support query like structures to pull together the data  

I am not familiar with the Beth Israel problem but my guess is the message was not hierarchical in nature
