### ISSUE TITLE
Missing datatype conversions in CCDA Map and qvto Build fails

### ISSUE THREAD

**Issue by KenLord** [MDMI/MDMI#118]
The following two datatype conversions cause an error running qvto transform.
[qvto:transformation] NEED MAPFILE IVL_TSToDateTimeMap.js
[qvto:transformation] NEED MAPFILE DateRangeToIVL_TSMap.js

These datatype conversions do not show up in the cda.mdmi map.

The build also fails in the conversion of mdmi file to xmi file

Transformation 'platform:/plugin/org.mdmi.qvt.transforms/transforms/Cda2Mdmi.qvto' has been executed
      [delete] Deleting: C:\Users\klord\MDMI-neon\git\maps\CDA\map\cdamap.xmi
        [copy] Copying 1 file to C:\Users\klord\MDMI-neon\git\maps\CDA\map
  [mdmiExport] Model has been exported to XMI

BUILD FAILED
C:\Users\klord\MDMI-neon\git\maps\CDA\cdatransform.xml:34: IOException in C:\Users\klord\MDMI-neon\git\maps\CDA\map\cdamap.xmi - java.io.IOException:Failed to delete C:\Users\klord\MDMI-neon\git\maps\CDA\map\cdamap.xmi while trying to rename C:\Users\klord\MDMI-neon\git\maps\CDA\map\rep4345411308391586870.tmp

**Comment by swmuir** [comment]
You need to exit the stand alone editor and the stand alone run time
The IO error is because windows does not allow you to delete open files


Did you create and issue This is on the mailing list ?

I will look into the IVL_TS to DateTime but we are not supposed to have date ranges

thanks

sean

**Comment by KenLord** [comment]
I will re-run the test with nothing open.

As for dateRange, I think you are correct.  So I will change the mappings.
I still think there might be an issue with pregancyEstimatedDeliveryDate
but let me check these out first.

**Comment by KenLord** [comment]
Closing issue and re-opening a new issue.  Issues of daterange and qvto of cda were not issues.
