### ISSUE TITLE
CCDA 1.1 Auto-generate: Accomodating Template IDs

### ISSUE THREAD

**Issue by KenLord** [MDMI/MDMI#17]
At the present time, we are generating one template id.  This can cause the following issues:
- if one is generating a CCDA document, there can be a required template id and an optional template id.  For a "generic" ccda map, we need to be able to process both.
- as we move to specific CCDA documents (eg CCD or Hospital Discharge), do we want to enforce the the use of the correct template id?  The general pattern has been to use MDHT for all validations and if we implement this using the required templateid then we won't move the information if the source message uses the optional template id.
- a similar issue is the 'versioning' issue where there will be different versions for the specific section.  My opinion is that we should support multiple versions in a map and let the validation process (eg in the IExHub) determine if it is a valid "transaction".

**Comment by swmuir** [comment]
Add optional and required  template id
