### ISSUE TITLE
CCDA 1.1 - AutoGen Medication Activity

### ISSUE THREAD

**Issue by KenLord** [MDMI/MDMI#24]
This is an example of how we need to annotate / couple the MDHT Model with the RI.

A Medication Activity can apply, for example, to a Medication Administered, a Medication Prescribed, or a  Medication Dispensed.  In the Referent Index, there are Business Elements representing Semantic Business Containers for each of those.  The Medication Activity needs to be mapped to the correct Business Element.  In addition, the moodCode and templateID when the CCDA 1.1 message is the target needs to be set appropriately.  

In addition, the child semantic elements of Medication Activity also need to be mapped to the set of Business Elements and there needs to be a data relationship based on the value of moodCode that determines exactly what Business Element should be used in the Mapping.

**Comment by swmuir** [comment]
Fixed
