### ISSUE TITLE
CCDA Auto Gen - Semantic Element Datatypes may differ from Business Element Datatypes

### ISSUE THREAD

**Issue by KenLord** [MDMI/MDMI#27]
This occurs with use of PersonName, Address, and Telecom because of the &use attribute in the CCDA model.

The Referent Index has two 2 Business Terms: one for PatientHomePhone and one for PatientMobilePhone.  The CCDA model should have a Semantic Element called PatientPhone with the &use attribute set to either HOME or CELL.  

We don;t handle this today. Two issues: 1) we need to annonate the CCDA model correctly and 2) we need to decide if the datatype in the RI contains the &use attribute and sets it or we eliminate the &use attribute and have different datatypes in the RI and maps.  XSI:type can also cause similar issues.

In process.

**Comment by swmuir** [comment]
Over taken by updates to transformation
