### ISSUE TITLE
Accessing RI Server from Eclipse Editor

### ISSUE THREAD

**Issue by KenLord** [MDMI/MDMI#55]
I went to access the RI.  Select Semantic Tab in Table View, select a semantic element, in bottom panel, select mapping tab.  I get prompted with url for RI Server.  I selected cancel.  The following error occurred: 
An error has occurred. See error log for more details.

Unable to reproduce in new build
GET http://52.22.81.254:8080/MDMISvc/bers?offset=0&count=100 returned a response status of 404 Not Found

**Comment by GOancea** [comment]
Sally: you need to use the new HTTP query stem (highlighted): 
http://52.22.81.254:8080/ org.mdmi.ri.service /bers?offset=0&count=100 

----- Original Message -----
