### ISSUE TITLE
CCDA 1.1 Automation: negationind affects semantic meaning

### ISSUE THREAD

**Issue by KenLord** [MDMI/MDMI#6]
This is the same issue as with the moodcode. negationind affects the semantic meaning of all the terms within a container.  For example, the vacine was administered or it wasn't administered.  Using the MDHT automation, we should recognize this situation and generate the correct mappings as well as set the negationind attribute to the correct value.

**Comment by swmuir** [comment]
Same as mood code - look at immunization map

**Comment by KenLord** [comment]
We have Business Elements that reflect the Semantic Meaning of negationIND when it occurs in the collection. Example is NotAProblem.
