### ISSUE TITLE
CCDA 1.1 - AG - Vital Sign Section

### ISSUE THREAD

**Issue by KenLord** [MDMI/MDMI#66]
Section Level
-	No text: Mapped and appears in source semantic model.

Organizer
o	No status code

Observation
-  Location of the container is incorrect: It is entryRelationship/observation[templateId[@root='2.16.840.1.113883.10.20.22.4.27']] and should be component/observation[templateId[@root='2.16.840.1.113883.10.20.22.4.27']]

Need to discuss the following:

Organizer Level
o	No effectiveTime.  I believe it is incorrect in source file.  Datatype is ivl_ts in MDHT / MDMI is dateRange and source message file contains <effectiveTime value="20140515"/>.  My assumption is this is incorrect in the source message.

**Comment by swmuir** [comment]
Ken - the model i have does not have the text for vital signs mapped - can you send me the latest uml model project

**Comment by KenLord** [comment]
This one has it ... thought I had sent it.

Sory
