### ISSUE TITLE
CCDA 1.1: Flattening of &use attribute

### ISSUE THREAD

**Issue by KenLord** [MDMI/MDMI#7]
For ease of use, we are "flattening" certain business terms so it is more obvious to the mapper what something means as well as not to have them understand what the structure is for a specfic format. An example is that the Referent Index does not have PatientTelecom as the term and requires instead that they map directly to PatientHomePhone or PatientCellPhone. Given this, we need to set the &use when the map is used as the target and conditionally map PatientTelecom based on the value of &use.

**Comment by swmuir** [comment]
ken to test
