### ISSUE TITLE
Codesystem and CodeSystem names 

### ISSUE THREAD

**Issue by KenLord** [MDMI/MDMI#76]
In the Referent Index Editor:
The Business Elements Panel there are four fields called enum value set, enum value field, enum value set field, and enum Value Description Field.
1)      We only need two fields and they should be labeled codeSystem and codeSystemName. They should be simple text boxes where the user types in the appropriate string. The values then update the same named attributes in the datatype for the Business Element.

a.       We do need to have a discussion of whether we can have multiple codeSystem / codeSystemName pairs but for next couple of weeks lets keep it simple.

2)      Please Reference Datatype up and just below Description.

In the New Eclipse Editor:
The same logic applies:  In the Semantic Element General MDMI panel, we need only two fields called codesystem and codeSystemName in the area of Value Set Data.

**Comment by SallyConway** [comment]
Renamed Terminology Reference and Terminology Authority per discussion.

SemanticElement model in Eclipse editor needs to be updated to have get/set methods to access these fields.

**Comment by KenLord** [comment]
closing the issue in ri editor ... will re-enter issue in Editor if needed
