### ISSUE TITLE
Proxy error in RI Editor when adding new Business Element

### ISSUE THREAD

**Issue by KenLord** [MDMI/MDMI#86]
launch RI Editor
- select "add new Business Element"
- add the new Business Element (name, description, datatype (assume it is not CodedElement and therefore does not need terminology references), uniqueID, and Semantic meta-data)
- select save edits from file menu
- select save all edits from File menu
- select save to web service from File menu
- exit application

one gets a Proxy error  (However, the changes have been saved to the web service)

**Comment by SallyConway** [comment]
Problem was caused when a new business element has associated meta-data. This has been fixed.
