### ISSUE TITLE
CCDA 1.1 Automation: Semantic Parents

### ISSUE THREAD

**Issue by KenLord** [MDMI/MDMI#9]
Definition: The Parent Semantic Element of any Semantic Element must be of type Normal and the associated Syntax Node must have a cardinality of >1.  

Rules: 
If the cardinality of a syntax node is >1 and the Semantic Element is a container, it must be of type Normal.
If the cardinality of a syntax node is 1, there is no Semantic Element, it is purely structural.  This is to ensure the Referent Index does not get burdened with structure based on a specfic healthcare message model.  for example, for the Semantic Element CONSOL_ALLERGYOBSERVATION_PARTICIPANT_PARTICIPANTROLE_PLAYINGENTITY_CODE, participant,participantrole, and playingentity are only structural and provide no additional semantic meaning or content. The Semantic Parent of the code should be AllergyObservation. There are many more examples.

**Comment by swmuir** [comment]
Done
